services:
  db:
    image: mysql:8.0
    container_name: armazon_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: c2880275_ventas
      MYSQL_USER: c2880275_ventas
      MYSQL_PASSWORD: wego76FIfe
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - "./nati30.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - optica-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  web:
    build: .
    container_name: armazon_web
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./certificados-afip:/var/www/certificados:ro
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: c2880275_ventas
      DB_PASSWORD: wego76FIfe
      DB_NAME: c2880275_ventas
      MAYORISTA_API_KEY: ${MAYORISTA_API_KEY:-}
    networks:
      - optica-network
      - edge_net

networks:
  optica-network:
    driver: bridge

  edge_net:
    external: true
    name: tienda3d_edge_net